MohamedHussien/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MohamedHussien.DAL.Repository.IRepository;
using MohamedHussien.Models;
using MohamedHussien.Utilities;

namespace MohamedHussien.Controllers
{
    [Authorize(Roles=SD.Role_Admin)]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWorkRepository unitOfWork;
        public CategoryController(IUnitOfWorkRepository unitOfWork)
        {
            this.unitOfWork = unitOfWork; 
        }
        public IActionResult Index()
        {
            List<Category> Data = unitOfWork.Category.GetAll().ToList();

            return View(Data);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Category Obj)
        {
            if (ModelState.IsValid)
            {
                unitOfWork.Category.Create(Obj);
                unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            Category categoryFromDb = unitOfWork.Category.GetByCondition(x => x.Id == id);
            return View(categoryFromDb);
        }
        [HttpPost]
        public IActionResult Update(Category obj)
        {
            Category categoryFromDb = unitOfWork.Category.GetByCondition(x => x.Id == obj.Id);
            categoryFromDb.Name = obj.Name;
            categoryFromDb.CategoryState = obj.CategoryState;
            unitOfWork.Save();
            TempData["success"] = " Category is Updated successfully  ";

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            Category categoryFromDb = unitOfWork.Category.GetByCondition(x => x.Id == id);

            return View(categoryFromDb);
        }
        [HttpPost]
        public IActionResult Delete(Category obj)
        {
            Category categoryFromDb = unitOfWork.Category.GetByCondition(x => x.Id == obj.Id);
            unitOfWork.Category.Delete(categoryFromDb);
            unitOfWork.Save();
            TempData["success"] = " Category is Deleted successfully  ";
            return RedirectToAction(nameof(Index));
        }

    }
}

MohamedHussien/Controllers/CompanyController.cs
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Mvc;
using MohamedHussien.DAL.Repository.IRepository;
using MohamedHussien.Models;

namespace MohamedHussien.Controllers
{
    public class CompanyController : Controller
    {
        private readonly IUnitOfWorkRepository unitOfWork;

        public CompanyController(IUnitOfWorkRepository UnitOfwork)
        {
            this.unitOfWork = UnitOfwork;
        }

        public IActionResult Index()
        {
            List<Company> data = unitOfWork.Company.GetAll().ToList();
            return View(data);
        }

        [HttpGet]
        public IActionResult Upsert(int?id )
        {
            
            if (id==null||id==0 )
            {
                return View(new Company()); 
            }
            else
            {
                Company data = unitOfWork.Company.GetByCondition(x => x.Id == id);
                return View(data); 
            }
        }

        [HttpPost]
        public IActionResult Upsert( Company company)
        {
            if (ModelState.IsValid)
            {
                if (company.Id == null||company.Id==0)
                {
                    unitOfWork.Company.Create(company);
                }
                else
                {
                    unitOfWork.Company.Update(company);

                }
                unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(company); 
            }
          


        }



        #region API Calls 
        [HttpGet]
        public IActionResult GetAll()
        {
            List<Company> obj = unitOfWork.Company.GetAll().ToList();
            unitOfWork.Save();
            return Json(new { data = obj });

        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var CompanyDeleted = unitOfWork.Company.GetByCondition(u => u.Id == id);
            if (CompanyDeleted == null)
            {
                return Json(new { success = false, message = " Error while deleting" });
            }
            unitOfWork.Company.Delete(CompanyDeleted);
            unitOfWork.Save();
            return Json(new { success = true, message = "Delete Successfully" });
        }
        #endregion

    }
}

MohamedHussien/Controllers/OrderController.cs
using E_Commerce.DAL.Repository;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MohamedHussien.DAL.Repository.IRepository;
using MohamedHussien.Models;
using MohamedHussien.Models.ViewModels;
using MohamedHussien.Utilities;
using Stripe;
using Stripe.Checkout;
using Stripe.Climate;
using System.Diagnostics;
using System.Security.Claims;

namespace MohamedHussien.Controllers
{
    [Authorize]
	public class OrderController : Controller
	{
		private readonly IUnitOfWorkRepository _UnitOfWork;
        [BindProperty]
        public OrderVM OrderVM { get; set; }
        public OrderController(IUnitOfWorkRepository UnitOfWork)
        {
			this._UnitOfWork = UnitOfWork; 
        }

        public IActionResult Index()
		{
			return View();
		}

        public IActionResult Details(int orderId )
        {
             OrderVM = new()
            {
                orderHeader = _UnitOfWork.OrderHeader.GetByCondition(u => u.Id == orderId, includeProperties: "applicationUser"),
                orderDetail = _UnitOfWork.OrderDetails.GetAll(u => u.OrderHeaderId == orderId, includeProperties: "Product").ToList()

            }; 
            return View(OrderVM);
        }

        [HttpPost]
        [Authorize(Roles =SD.Role_Admin+","+SD.Role_Employee)]
        public IActionResult UpdateOrderDetailsl( )
        {
            var orderHeaderFromDb = _UnitOfWork.OrderHeader.GetByCondition(u => u.Id == OrderVM.orderHeader.Id);
            orderHeaderFromDb.Name = OrderVM.orderHeader.Name; 
            orderHeaderFromDb.Phone = OrderVM.orderHeader.Phone; 
            orderHeaderFromDb.StreetAdress = OrderVM.orderHeader.StreetAdress; 
            orderHeaderFromDb.City = OrderVM.orderHeader.City; 
            orderHeaderFromDb.State = OrderVM.orderHeader.State; 
            orderHeaderFromDb.PostalCode = OrderVM.orderHeader.PostalCode;
            _UnitOfWork.OrderHeader.Update(orderHeaderFromDb);
            _UnitOfWork.Save();
            TempData["Success"] = "Order Details is updated successfully";

            return RedirectToAction(nameof(Details), new { orderId = orderHeaderFromDb.Id }); 
        }

        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        public IActionResult StrtProcessing()
        {
            _UnitOfWork.OrderHeader.UpdateStatus(OrderVM.orderHeader.Id, SD.StatusInProcess);
            _UnitOfWork.Save();
            TempData["Success"] = "Order Details is updated successfully";
            return RedirectToAction(nameof(Details), new { orderId = OrderVM.orderHeader.Id }); 

        }
        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        public IActionResult ShipOrder()
        {
            var orderHeader = _UnitOfWork.OrderHeader.GetByCondition(u => u.Id == OrderVM.orderHeader.Id);
            orderHeader.OrderStatus = SD.StatusShipped;
            orderHeader.ShippingDate = DateTime.Now;
            if (orderHeader.PaymentStatus==SD.PaymentStatusDelayedApproved)
            {
                orderHeader.PaymentDueDate = DateTime.Now.AddDays(30); 
            }
            _UnitOfWork.OrderHeader.Update(orderHeader);
            _UnitOfWork.Save();
            return RedirectToAction(nameof(Details),new { orderId = OrderVM.orderHeader.Id }); 
        }
        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        public IActionResult CancelOrder()
        {
            var orderHeader = _UnitOfWork.OrderHeader.GetByCondition(u => u.Id == OrderVM.orderHeader.Id);
            if (orderHeader.PaymentStatus==SD.PaymentStatusApproved)
            {
                var options = new RefundCreateOptions
                {
                    Reason = RefundReasons.RequestedByCustomer,
                    PaymentIntent = orderHeader.PaymentIntentId
                };
                var service = new RefundService();
                Refund refund = service.Create(options);
                _UnitOfWork.OrderHeader.UpdateStatus(orderHeader.Id, SD.StatusCancelled, SD.StatusReFunded); 
            }
            else
            {
                _UnitOfWork.OrderHeader.UpdateStatus(orderHeader.Id, SD.StatusCancelled, SD.StatusReFunded); 
            }
            _UnitOfWork.Save();
            return RedirectToAction(nameof(Details), new { orderId = OrderVM.orderHeader.Id });
        }
        [HttpPost]
        [ActionName("Details")]  
        public IActionResult Details_Pay_Now()
        {
            OrderVM.orderHeader = _UnitOfWork.OrderHeader
                .GetByCondition(u => u.Id == OrderVM.orderHeader.Id,includeProperties: "applicationUser");
            OrderVM.orderDetail = _UnitOfWork.OrderDetails
                .GetAll(u => u.OrderHeaderId == OrderVM.orderHeader.Id,includeProperties: "Product").ToList();
            var domain = "https://localhost:7066/";
            var options = new Stripe.Checkout.SessionCreateOptions
            {
                SuccessUrl = domain + $"Order/OrderConfirmation?orderHeaderId={OrderVM.orderHeader.Id}",
                CancelUrl = domain + $"Order/Details?orderId={OrderVM.orderHeader.Id}",
                LineItems = new List<Stripe.Checkout.SessionLineItemOptions>(),
                Mode = "payment",
            };

            foreach (var item in OrderVM.orderDetail)
            {
                var sessionLineItem = new SessionLineItemOptions
                {

                    PriceData = new SessionLineItemPriceDataOptions
                    {

                        UnitAmount = (long)(item.Price * 100),
                        Currency = "usd",
                        ProductData = new SessionLineItemPriceDataProductDataOptions
                        {
                            Name = item.Product.Title
                        }
                    },
                    Quantity = item.Count
                };
                options.LineItems.Add(sessionLineItem);
            }
            var service = new Stripe.Checkout.SessionService();
            Session session = service.Create(options);
            _UnitOfWork.OrderHeader.UpdateStripePaymentId(OrderVM.orderHeader.Id, session.Id, session.PaymentIntentId);
            _UnitOfWork.Save();
            Response.Headers.Add("Location", session.Url);
            return new StatusCodeResult(303);

        }
        public IActionResult OrderConfirmation(int orderHeaderId )
        {
            OrderHeader orderHeader = _UnitOfWork.OrderHeader.GetByCondition(u => u.Id == orderHeaderId);
            if (orderHeader.PaymentStatus == SD.PaymentStatusDelayedApproved)
            {
                var service = new SessionService();
                Session session = service.Get(orderHeader.SessionId);
                if (session.PaymentStatus.ToLower() == "paid")
                {
                    _UnitOfWork.OrderHeader.UpdateStripePaymentId(orderHeaderId, session.Id, session.PaymentIntentId);
                    _UnitOfWork.OrderHeader.UpdateStatus(orderHeaderId, SD.StatusApproved, SD.PaymentStatusApproved);
                    _UnitOfWork.Save();
                }
            }
            return View(orderHeaderId);

        }
        #region API Calls 
        [HttpGet]
		public IActionResult GetAll(string status)
		{
            IEnumerable<OrderHeader> obj; 
            if (User.IsInRole(SD.Role_Admin)||User.IsInRole(SD.Role_Employee))
            {
                obj= _UnitOfWork.OrderHeader.GetAll(includeProperties: "applicationUser").ToList();
            }
            else
            {
                var claimsIdentity = (ClaimsIdentity)User.Identity;

                var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
                obj = _UnitOfWork.OrderHeader.GetAll(u => u.ApplicationUserId == userId, includeProperties: "applicationUser"); 
                    
            }
            switch (status)
            {
                case "pending":
                    obj = obj.Where(u => u.PaymentStatus == SD.PaymentStatusDelayedApproved); 
                          break;
                case "inProcess":
                    obj = obj.Where(u => u.OrderStatus == SD.StatusInProcess); 
                          break;
                case "completed":
                    obj = obj.Where(u => u.OrderStatus == SD.StatusShipped);
                          break;
                case "approved":
                    obj = obj.Where(u => u.OrderStatus == SD.StatusApproved);
                         break;
                default:
                         break;
            }
            return Json(new { data = obj });
		}
		#endregion
	}
}

MohamedHussien/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MohamedHussien</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">E_Commerce</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">

                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link " asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Order" asp-action="Index">Manage Order</a>
                        </li>

                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item ">
                                <a class="nav-link " asp-controller="Category" asp-action="Index">Category</a>
                            </li>

                            <li class="nav-item ">
                                <a class="nav-link" asp-controller="Product" asp-action="Index">Product</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link " asp-controller="Company" asp-action="Index">Company</a>
                            </li>
                        }
                        <li class="nav-item col-4">
                            <a class="nav-link" asp-controller="Customer" asp-action="Index">
                                <i class="bi bi-cart col-4">  </i>&nbsp
                            </a>
                        </li>


                    </ul>
                    <div> <partial name="_LoginPartial" /></div>


                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MohamedHussien - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>